#import "../../src/lib.typ" as yade

#set page(width: auto, height:auto, margin: 0%)

#show : yade.yade

```yade
{"graph":{"activeTabId":0,"latexBackgroundColor":"white","latexPreamble":"\\newcommand{\\coqproof}[1]{\\checkmark}","nextTabId":1,"tabs":[{"edges":[{"from":0,"id":16,"label":{"label":"a","options":{},"zindex":0},"to":1},{"from":2,"id":17,"label":{"label":"a","options":{"alignment":"right"},"zindex":0},"to":3},{"from":4,"id":18,"label":{"label":"a","options":{},"zindex":0},"to":5},{"from":6,"id":19,"label":{"label":"a","options":{"alignment":"right"},"zindex":0},"to":7},{"from":8,"id":20,"label":{"label":"a","options":{},"zindex":0},"to":9},{"from":10,"id":21,"label":{"label":"a","options":{"alignment":"right"},"zindex":0},"to":11},{"from":12,"id":22,"label":{"label":"a","options":{},"zindex":0},"to":13},{"from":14,"id":23,"label":{"label":"a","options":{"alignment":"right"},"zindex":0},"to":15}],"freehandDrawings":[],"id":0,"nextGraphId":24,"nodes":[{"id":0,"label":{"label":"","options":{},"pos":[91,117],"zindex":0}},{"id":1,"label":{"label":"","options":{},"pos":[169,117],"zindex":0}},{"id":2,"label":{"label":"","options":{},"pos":[247,117],"zindex":0}},{"id":3,"label":{"label":"","options":{},"pos":[325,117],"zindex":0}},{"id":4,"label":{"label":"","options":{},"pos":[91,195],"zindex":0}},{"id":5,"label":{"label":"","options":{},"pos":[91,273],"zindex":0}},{"id":6,"label":{"label":"","options":{},"pos":[247,195],"zindex":0}},{"id":7,"label":{"label":"","options":{},"pos":[247,273],"zindex":0}},{"id":8,"label":{"label":"","options":{},"pos":[481,117],"zindex":0}},{"id":9,"label":{"label":"","options":{},"pos":[403,117],"zindex":0}},{"id":10,"label":{"label":"","options":{},"pos":[637,117],"zindex":0}},{"id":11,"label":{"label":"","options":{},"pos":[559,117],"zindex":0}},{"id":12,"label":{"label":"","options":{},"pos":[403,273],"zindex":0}},{"id":13,"label":{"label":"","options":{},"pos":[403,195],"zindex":0}},{"id":14,"label":{"label":"","options":{},"pos":[559,273],"zindex":0}},{"id":15,"label":{"label":"","options":{},"pos":[559,195],"zindex":0}}],"sizeGrid":26,"title":"1"}]},"version":20}
```
