#import "../../src/lib.typ" as yade

#set page(width: auto, height:auto, margin: 0%)

#show : yade.yade

#set align(center)

```yade
{"graph":{"activeTabId":0,"latexBackgroundColor":"white","latexPreamble":"\\newcommand{\\coqproof}[1]{\\checkmark}","nextTabId":1,"tabs":[{"edges":[{"from":0,"id":6,"label":{"label":"","options":{},"zindex":0},"to":1},{"from":2,"id":7,"label":{"label":"","options":{"head":"none"},"zindex":0},"to":3},{"from":4,"id":8,"label":{"label":"","options":{"head":"twoheads"},"zindex":0},"to":5}],"freehandDrawings":[],"id":0,"nextGraphId":9,"nodes":[{"id":0,"label":{"label":"","options":{},"pos":[143,143],"zindex":0}},{"id":1,"label":{"label":"","options":{},"pos":[221,143],"zindex":0}},{"id":2,"label":{"label":"","options":{},"pos":[325,143],"zindex":0}},{"id":3,"label":{"label":"","options":{},"pos":[403,143],"zindex":0}},{"id":4,"label":{"label":"","options":{},"pos":[507,143],"zindex":0}},{"id":5,"label":{"label":"","options":{},"pos":[585,143],"zindex":0}}],"sizeGrid":26,"title":"1"}]},"version":20}
```

```yade
{"graph":{"activeTabId":0,"latexBackgroundColor":"white","latexPreamble":"\\newcommand{\\coqproof}[1]{\\checkmark}","nextTabId":1,"tabs":[{"edges":[{"from":0,"id":6,"label":{"label":"","options":{"tail":"hook"},"zindex":0},"to":1},{"from":2,"id":7,"label":{"label":"","options":{"tail":"hook","head":"none"},"zindex":0},"to":3},{"from":4,"id":8,"label":{"label":"","options":{"tail":"hook","head":"twoheads"},"zindex":0},"to":5}],"freehandDrawings":[],"id":0,"nextGraphId":9,"nodes":[{"id":0,"label":{"label":"","options":{},"pos":[143,195],"zindex":0}},{"id":1,"label":{"label":"","options":{},"pos":[221,195],"zindex":0}},{"id":2,"label":{"label":"","options":{},"pos":[325,195],"zindex":0}},{"id":3,"label":{"label":"","options":{},"pos":[403,195],"zindex":0}},{"id":4,"label":{"label":"","options":{},"pos":[507,195],"zindex":0}},{"id":5,"label":{"label":"","options":{},"pos":[585,195],"zindex":0}}],"sizeGrid":26,"title":"1"}]},"version":20}
```

```yade
{"graph":{"activeTabId":0,"latexBackgroundColor":"white","latexPreamble":"\\newcommand{\\coqproof}[1]{\\checkmark}","nextTabId":1,"tabs":[{"edges":[{"from":0,"id":6,"label":{"label":"","options":{"tail":"hookalt"},"zindex":0},"to":1},{"from":2,"id":7,"label":{"label":"","options":{"tail":"hookalt","head":"none"},"zindex":0},"to":3},{"from":4,"id":8,"label":{"label":"","options":{"tail":"hookalt","head":"twoheads"},"zindex":0},"to":5}],"freehandDrawings":[],"id":0,"nextGraphId":9,"nodes":[{"id":0,"label":{"label":"","options":{},"pos":[143,247],"zindex":0}},{"id":1,"label":{"label":"","options":{},"pos":[221,247],"zindex":0}},{"id":2,"label":{"label":"","options":{},"pos":[325,247],"zindex":0}},{"id":3,"label":{"label":"","options":{},"pos":[403,247],"zindex":0}},{"id":4,"label":{"label":"","options":{},"pos":[507,247],"zindex":0}},{"id":5,"label":{"label":"","options":{},"pos":[585,247],"zindex":0}}],"sizeGrid":26,"title":"1"}]},"version":20}
```

```yade
{"graph":{"activeTabId":0,"latexBackgroundColor":"white","latexPreamble":"\\newcommand{\\coqproof}[1]{\\checkmark}","nextTabId":1,"tabs":[{"edges":[{"from":0,"id":6,"label":{"label":"","options":{"tail":"arrowtail"},"zindex":0},"to":1},{"from":2,"id":7,"label":{"label":"","options":{"tail":"arrowtail","head":"none"},"zindex":0},"to":3},{"from":4,"id":8,"label":{"label":"","options":{"tail":"arrowtail","head":"twoheads"},"zindex":0},"to":5}],"freehandDrawings":[],"id":0,"nextGraphId":9,"nodes":[{"id":0,"label":{"label":"","options":{},"pos":[143,299],"zindex":0}},{"id":1,"label":{"label":"","options":{},"pos":[221,299],"zindex":0}},{"id":2,"label":{"label":"","options":{},"pos":[325,299],"zindex":0}},{"id":3,"label":{"label":"","options":{},"pos":[403,299],"zindex":0}},{"id":4,"label":{"label":"","options":{},"pos":[507,299],"zindex":0}},{"id":5,"label":{"label":"","options":{},"pos":[585,299],"zindex":0}}],"sizeGrid":26,"title":"1"}]},"version":20}
```

```yade
{"graph":{"activeTabId":0,"latexBackgroundColor":"white","latexPreamble":"\\newcommand{\\coqproof}[1]{\\checkmark}","nextTabId":1,"tabs":[{"edges":[{"from":0,"id":6,"label":{"label":"","options":{"tail":"mapsto"},"zindex":0},"to":1},{"from":2,"id":7,"label":{"label":"","options":{"tail":"mapsto","head":"none"},"zindex":0},"to":3},{"from":4,"id":8,"label":{"label":"","options":{"tail":"mapsto","head":"twoheads"},"zindex":0},"to":5}],"freehandDrawings":[],"id":0,"nextGraphId":9,"nodes":[{"id":0,"label":{"label":"","options":{},"pos":[143,351],"zindex":0}},{"id":1,"label":{"label":"","options":{},"pos":[221,351],"zindex":0}},{"id":2,"label":{"label":"","options":{},"pos":[325,351],"zindex":0}},{"id":3,"label":{"label":"","options":{},"pos":[403,351],"zindex":0}},{"id":4,"label":{"label":"","options":{},"pos":[507,351],"zindex":0}},{"id":5,"label":{"label":"","options":{},"pos":[585,351],"zindex":0}}],"sizeGrid":26,"title":"1"}]},"version":20}
```

```yade
{"graph":{"activeTabId":0,"latexBackgroundColor":"white","latexPreamble":"\\newcommand{\\coqproof}[1]{\\checkmark}","nextTabId":1,"tabs":[{"edges":[{"from":0,"id":16,"label":{"label":"","options":{"headColor":"blue","tail":"hook"},"zindex":0},"to":1},{"from":2,"id":17,"label":{"label":"","options":{"headColor":"orange","tailColor":"green","tail":"hookalt"},"zindex":0},"to":3},{"from":4,"id":18,"label":{"label":"","options":{"headColor":"purple","tailColor":"red","tail":"arrowtail"},"zindex":0},"to":5},{"from":6,"id":19,"label":{"label":"","options":{"headColor":"gray","tailColor":"yellow","tail":"mapsto"},"zindex":0},"to":7},{"from":8,"id":20,"label":{"label":"","options":{"headColor":"green","tailColor":"blue","tail":"hook","head":"twoheads"},"zindex":0},"to":9},{"from":10,"id":21,"label":{"label":"","options":{"headColor":"red","tailColor":"orange","tail":"hookalt","head":"twoheads"},"zindex":0},"to":11},{"from":12,"id":22,"label":{"label":"","options":{"headColor":"yellow","tailColor":"purple","tail":"arrowtail","head":"twoheads"},"zindex":0},"to":13},{"from":14,"id":23,"label":{"label":"","options":{"tailColor":"gray","tail":"mapsto","head":"twoheads"},"zindex":0},"to":15}],"freehandDrawings":[],"id":0,"nextGraphId":24,"nodes":[{"id":0,"label":{"label":"","options":{},"pos":[143,195],"zindex":0}},{"id":1,"label":{"label":"","options":{},"pos":[221,195],"zindex":0}},{"id":2,"label":{"label":"","options":{},"pos":[143,247],"zindex":0}},{"id":3,"label":{"label":"","options":{},"pos":[221,247],"zindex":0}},{"id":4,"label":{"label":"","options":{},"pos":[143,299],"zindex":0}},{"id":5,"label":{"label":"","options":{},"pos":[221,299],"zindex":0}},{"id":6,"label":{"label":"","options":{},"pos":[143,351],"zindex":0}},{"id":7,"label":{"label":"","options":{},"pos":[221,351],"zindex":0}},{"id":8,"label":{"label":"","options":{},"pos":[299,195],"zindex":0}},{"id":9,"label":{"label":"","options":{},"pos":[377,195],"zindex":0}},{"id":10,"label":{"label":"","options":{},"pos":[299,247],"zindex":0}},{"id":11,"label":{"label":"","options":{},"pos":[377,247],"zindex":0}},{"id":12,"label":{"label":"","options":{},"pos":[299,299],"zindex":0}},{"id":13,"label":{"label":"","options":{},"pos":[377,299],"zindex":0}},{"id":14,"label":{"label":"","options":{},"pos":[299,351],"zindex":0}},{"id":15,"label":{"label":"","options":{},"pos":[377,351],"zindex":0}}],"sizeGrid":26,"title":"1"}]},"version":20}
```
